#!/bin/sh

#update-alternatives --install /usr/bin/x-session-manager \
#    x-session-manager /usr/local/bin/concerto 50

cat > /etc/network/interfaces << EOF

auto lo
iface lo inet loopback

allow-hotplug eth0
iface eth0 inet dhcp

allow-hotplug wlan0
iface wlan0 inet manual
    wpa-roam /etc/wpa_supplicant.conf

iface default inet dhcp

EOF

cat > /etc/wpa_supplicant.conf << EOF
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
network={
    ssid="blah"
    psk="phuphek9"
}

EOF
