#!/bin/sh

# Find any gems that were added to the boot media and install them.

Gem_hack ()
{

	echo -n " gem_hack"

	Configure_gem_hack
}

Configure_gem_hack ()
{
	if [ -d /live/image/install_gems ]
	then
		find /live/image/install_gems -iname '*.gem' -exec gem install \{\} \;
	fi
}

Gem_hack
